version: '3.4'

services: 

  frontend:
    image: store:latest
    environment: 
      - ProductEndpoint=http://backend:8080
      - ConnectionStrings:AppConfig=Endpoint=https://eshop-app-features2649719387.azconfig.io;Id=efXu;Secret=96ajvScNe0IwCJas0dQjWBnRxl9lm8ewMiB4boMBiIhkMZMrA0YlJQQJ99AEAC5RqLJOuM6YAAACAZACl1so
    ports:
      - "32000:8080"
    depends_on: 
      - backend
  backend:
    image: products:latest
    ports: 
      - "32001:8080"